config/routes.rb
Rails.application.routes.draw do
  root "accounts#index"
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  resources :accounts
end

app/models/account.rb
class Account < ApplicationRecord
    has_many :repos, dependent: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/repo.rb
class Repo < ApplicationRecord
    belongs_to :account
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :set_account, only: [:update, :destroy, :show, :edit]

  def set_account
    @account = Account.find(params[:id])
    @repos = Repo.where("account_id": params[:id])
    print @repos
  end

  def create
    nick_name = params["account"]["nick_name"].downcase
    exist = Account.where("nick_name": nick_name).pluck(:id)
    
    if exist != []
      redirect_to account_path(exist)
    else
      require "github_info"
      github_info = GithubInfo.new(nick_name)
      repos_data = github_info.repos
      
      user_name, repos = repos_data

      if user_name == "Warning"
        redirect_to new_account_path
      else
        account = Account.create(
          nick_name: nick_name,
          user_name:user_name,
          )
        repos.each do |repo_name|
          Repo.create(
            account_id: account[:id],
            repo_name: repo_name
          )
        end
        redirect_to account_path(account)
      end
    end
  end

  def update
    @account.update(
      nick_name: params[:account][:nick_name],
      user_name: params[:account][:user_name],
    )
    redirect_to account_path(@account)
  end

  def destroy
    @account.destroy
    redirect_to account_path(accounts_path)
  end

  def show
  end

  def index
    @accounts = Account.all
  end

  def new
    @account = Account.new
  end

  def edit
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/github_info.rb
# require_relative "rubygems"
# require_relative "httparty"

class GithubInfo
    include HTTParty
    base_uri "https://api.github.com/users/"

    def initialize(nick_name)
        @account_nick_name = nick_name
    end

    # def account
    #     self.class.get("/" + @account_nick_name.to_s).parsed_response["name"]
    # end

    def repos
        account_info = self.class.get("/" + @account_nick_name.to_s)

        if account_info.code != 200
            return ["Warning", "Cannot find account #{@account_nick_name}"]
        else
            account_name = account_info.parsed_response["name"]
            repo_names = []
            # print self.account "\n"
            self.class.get("/" + @account_nick_name.to_s + "/repos").each do |repo|
                repo_names.append(repo["name"])
            end
            return [account_name, repo_names]
        end
    end
end



    # def retrive_name(response)
    #     response.each do |data|
    #         print data.parsed_response["name"]
    #     end
    # end

    # def acc_info(response)
    #     if response
    #         response
    #     else
    #         "Cannot find account #{@account_nick_name}"
    #     end
    # end


# github_info = GithubInfo.new("therobotisnotatoy")
# github_info.repos



# print github_info.account
# print github_info.repos
# if not github_info.account["name"]
#     print "Cannot find account #{@account_nick_name}"
# else
#     print github_info.account["name"] + "\n"

#     github_info.repos.each do |repo|
#         print " - " + repo["name"] + "\n"
#     end
# end

app/controllers/graphql_controller.rb
class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = prepare_variables(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]
    context = {
      # Query context goes here, for example:
      # current_user: current_user,
    }
    result = GithubReposSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?
    handle_error_in_development(e)
  end

  private

  # Handle variables in form data, JSON body, or a blank value
  def prepare_variables(variables_param)
    case variables_param
    when String
      if variables_param.present?
        JSON.parse(variables_param) || {}
      else
        {}
      end
    when Hash
      variables_param
    when ActionController::Parameters
      variables_param.to_unsafe_hash # GraphQL-Ruby will validate name and type of incoming variables.
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{variables_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/create.html.erb
<h1>Find account</h1>

<%= button_to "Homepage", accounts_path, method: :get %>

<%= form_with model: @account do |form| %>
  <p>
    <%= form.label :nick_name, "Nikname: " %>
    <%= form.text_field :nick_name %>
  </p>
  <p>
    <%= form.submit "Search"%>
  </p>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit account</h1>

<%= button_to "Homepage", accounts_path, method: :get %>

<%= form_with model: @account do |form| %>
  <p>
    <%= form.label :nick_name, "Nikname: " %>
    <%= form.text_field :nick_name, options = {:autofocus => true } %>
  </p>
  <p>
    Name: <%= form.text_field :user_name %>
  </p>
  <p>
    <%= form.submit "Save"%>
  </p>
<% end %>

app/views/accounts/index.html.erb
<h1>Account manager</h1>

<%= button_to "Add account", new_account_path, method: :get %>

<p>
  Repositories:
</p>

<% @accounts.each do |account| %>
  <p>
  &nbsp;&nbsp;-&nbsp;
    <%= link_to "#{account.nick_name}", account_path(id: account.id) %>
    <%= button_to "Edit", edit_account_path(account), method: :get %>
    <%= button_to "Remove", account_path(account), method: :delete %>
  </p>
<% end %>

app/views/accounts/new.html.erb
<h1>Find account</h1>

<%= form_with model: @account do |form| %>
  <p><%= link_to "Homepage", accounts_path %></p>
  <p>
    <%= form.label :nick_name, "Nikname: " %>
    <%= form.text_field :nick_name %>
  </p>
  <p>Name: <%= form.text_field :user_name %></p>
  <p>Reps: <%= form.text_field :repos %></p>
  <p><%= form.submit "Search"%></p>
<% end %>

app/views/accounts/show.html.erb
<h1>Account Info</h1>

<%= button_to "Homepage", accounts_path, method: :get %>

<p>
  Nickname: 
  <%= link_to @account.nick_name, "https://github.com/#{@account.nick_name}" %>
</p>
<p>
  Name: 
  <%= @account.user_name %>
</p>
<p>
  Repositories:
</p>

<% @repos.each do |repo| %>
  <p>
    &nbsp;&nbsp;-&nbsp;
    <%= link_to repo.repo_name, "https://github.com/#{@account.nick_name}/#{repo.repo_name}" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GithubRepos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>